### ISSUE TITLE
How to integrate with current QLDB's node SDK?

### ISSUE THREAD

**Issue by joaomilho** [amzn/ion-hash-js#35]
It's a bit unclear how this lib integrates with current QLDB's node SDK (last version from July 2019 I think), specifically in order to set the commit hash. Would be great if you could provide some examples!

Thanks a lot.

**Comment by siddsanyal** [comment]
In terms of examples, Amazon QLDB released a preview version of the Python driver to GitHub: github.com/awslabs/amazon-qldb-driver-python (also see https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.python.html). If you're familiar with Python you should be able to derive a hash solution for Node.js. Please note that we are working on a preview version of the Amazon QLDB Node.js driver that should be available shortly. We would encourage you to review the Python implementation https://github.com/awslabs/amazon-qldb-driver-python/blob/master/pyqldb/util/qldb_hash.py.
As a reference, one of the answers for this Stackoverflow discussion explains the hash algorithm used https://stackoverflow.com/a/57964721/12115342.

Best Regards

**Comment by pbcornell** [comment]
A preview version of the Amazon QLDB Node.js driver is now available; see [Node.js and Amazon QLDB](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.nodejs.html) for more information.

**Comment by pbcornell** [comment]
No additional activity here, closing.  Feel free to re-open or open a new issue if you have additional questions.
